const TOPIC_SUBDIVISIONS = {
  'Biblical Studies': ['Old Testament', 'New Testament', 'Biblical Theology', 'Biblical Archaeology', 'Biblical Languages'],
  'Old Testament': ['Torah', 'Prophets', 'Historical Books', 'Wisdom Literature', 'Psalms'],
  'Torah': [],
  'Prophets': [],
  'Historical Books': [],
  'Wisdom Literature': [],
  'Psalms': [],
  'New Testament': ['Gospels', 'Epistles', 'Revelation', 'Acts', 'Pauline Theology'],
  'Gospels': [],
  'Epistles': [],
  'Revelation': [],
  'Acts': [],
  'Pauline Theology': [],
  'Biblical Theology': [],
  'Biblical Archaeology': [],
  'Biblical Languages': [],
  'Comparative Religion': [],
  'Religious Philosophy': [],
  'Mythology': ['Greek Mythology', 'Roman Mythology', 'Norse Mythology', 'Hindu Mythology', 'Egyptian Mythology'],
  'Greek Mythology': [],
  'Roman Mythology': [],
  'Norse Mythology': [],
  'Egyptian Mythology': [],
  'Arts': ['Literature', 'Visual Arts', 'Performing Arts', 'Music', 'Design'],
  'Literature': ['Fiction', 'Poetry', 'Drama', 'Literary Theory', 'World Literature', 'Classics', 'Essays', 'Narrative Forms'],
  'Fiction': ['Novels', 'Short Stories', 'Science Fiction', 'Fantasy', 'Historical Fiction', 'Literary Fiction'],
  'Novels': ['Victorian Novel', 'Modern Novel', 'Postmodern Novel', 'Contemporary Novel', 'Experimental Fiction', 'Realism'],
  'Victorian Novel': [],
  'Modern Novel': [],
  'Postmodern Novel': [],
  'Contemporary Novel': [],
  'Experimental Fiction': [],
  'Realism': [],
  'Short Stories': [],
  'Science Fiction': [],
  'Fantasy': [],
  'Historical Fiction': [],
  'Literary Fiction': [],
  'Poetry': ['Ancient Poetry', 'Medieval Poetry', 'Renaissance Poetry', 'Romantic Poetry', 'Modern Poetry', 'Contemporary Poetry', 'Epic Poetry', 'Lyric Poetry'],
  'Ancient Poetry': [],
  'Medieval Poetry': [],
  'Renaissance Poetry': [],
  'Romantic Poetry': [],
  'Modern Poetry': [],
  'Contemporary Poetry': [],
  'Epic Poetry': [],
  'Lyric Poetry': [],
  'Drama': ['Comedy', 'Tragedy', 'Tragicomedy', 'Classical Drama', 'Modern Drama', 'Contemporary Drama', 'Melodrama'],
  'Comedy': [],
  'Tragedy': [],
  'Tragicomedy': [],
  'Classical Drama': [],
  'Modern Drama': [],
  'Contemporary Drama': [],
  'Melodrama': [],
  'Literary Theory': ['Structuralism', 'Deconstruction', 'Rhetoric', 'Semiotics', 'Narratology', 'Literary Criticism'],
  'Structuralism': [],
  'Deconstruction': [],
  'Rhetoric': [],
  'Semiotics': [],
  'Narratology': [],
  'Literary Criticism': [],
  'World Literature': [],
  'Classics': [],
  'Essays': [],
  'Narrative Forms': [],
  'Visual Arts': ['Painting', 'Sculpture', 'Architecture', 'Photography', 'Film', 'Installation Art', 'Digital Art', 'Graphic Design', 'Printmaking'],
  'Painting': ['Renaissance Painting', 'Baroque Painting', 'Impressionism', 'Modernism', 'Abstract Art', 'Contemporary Painting', 'Color Theory', 'Technique'],
  'Renaissance Painting': [],
  'Baroque Painting': [],
  'Impressionism': [],
  'Modernism': [],
  'Abstract Art': [],
  'Contemporary Painting': [],
  'Color Theory': [],
  'Technique': [],
  'Sculpture': ['Classical Sculpture', 'Renaissance Sculpture', 'Modern Sculpture', 'Public Sculpture', 'Installation Sculpture', 'Contemporary Sculpture'],
  'Classical Sculpture': [],
  'Renaissance Sculpture': [],
  'Modern Sculpture': [],
  'Public Sculpture': [],
  'Installation Sculpture': [],
  'Contemporary Sculpture': [],
  'Architecture': ['Classical Architecture', 'Medieval Architecture', 'Renaissance Architecture', 'Modern Architecture', 'Postmodern Architecture', 'Contemporary Architecture', 'Architectural Theory', 'Urban Design'],
  'Classical Architecture': [],
  'Medieval Architecture': [],
  'Renaissance Architecture': [],
  'Modern Architecture': [],
  'Postmodern Architecture': [],
  'Contemporary Architecture': [],
  'Architectural Theory': [],
  'Urban Design': [],
  'Photography': ['Black and White Photography', 'Color Photography', 'Documentary Photography', 'Fine Art Photography', 'Photojournalism'],
  'Black and White Photography': [],
  'Color Photography': [],
  'Documentary Photography': [],
  'Fine Art Photography': [],
  'Photojournalism': [],
  'Film': ['Film History', 'Film Theory', 'Cinematography', 'Film Genres', 'Film Criticism', 'Animation', 'Documentary Film'],
  'Film History': [],
  'Film Theory': [],
  'Cinematography': [],
  'Film Genres': [],
  'Film Criticism': [],
  'Animation': [],
  'Documentary Film': [],
  'Installation Art': [],
  'Digital Art': ['Digital Painting', 'Digital Sculpture', 'Virtual Reality Art', 'Generative Art', 'Interactive Art'],
  'Digital Painting': [],
  'Digital Sculpture': [],
  'Virtual Reality Art': [],
  'Generative Art': [],
  'Interactive Art': [],
  'Graphic Design': ['Typography', 'Logo Design', 'Web Design', 'Branding', 'Layout Design'],
  'Typography': [],
  'Logo Design': [],
  'Web Design': [],
  'Branding': [],
  'Layout Design': [],
  'Printmaking': [],
  'Performing Arts': ['Theatre', 'Dance', 'Performance Art', 'Musical Theatre'],
  'Theatre': ['Classical Theatre', 'Modern Theatre', 'Contemporary Theatre', 'Theatre Theory', 'Directing', 'Acting', 'Stage Design'],
  'Classical Theatre': [],
  'Modern Theatre': [],
  'Contemporary Theatre': [],
  'Theatre Theory': [],
  'Directing': [],
  'Acting': [],
  'Stage Design': [],
  'Dance': ['Classical Dance', 'Modern Dance', 'Contemporary Dance', 'Ballet', 'Jazz Dance', 'Hip Hop Dance'],
  'Classical Dance': [],
  'Modern Dance': [],
  'Contemporary Dance': [],
  'Ballet': [],
  'Jazz Dance': [],
  'Hip Hop Dance': [],
  'Performance Art': [],
  'Musical Theatre': [],
  'Music': ['Classical Music', 'Jazz', 'Rock', 'Pop', 'World Music', 'Electronic Music', 'Music Theory', 'Composition'],
  'Classical Music': ['Baroque', 'Classical Period', 'Romantic', 'Modern Classical', 'Contemporary Classical', 'Opera', 'Orchestral Music', 'Chamber Music'],
  'Baroque': [],
  'Classical Period': [],
  'Romantic': [],
  'Modern Classical': [],
  'Contemporary Classical': [],
  'Orchestral Music': [],
  'Chamber Music': [],
  'Jazz': ['Early Jazz', 'Swing', 'Bebop', 'Cool Jazz', 'Free Jazz', 'Fusion', 'Modal Jazz', 'Jazz Standards'],
  'Early Jazz': [],
  'Swing': [],
  'Bebop': [],
  'Cool Jazz': [],
  'Free Jazz': [],
  'Fusion': [],
  'Modal Jazz': [],
  'Jazz Standards': [],
  'Rock': ['Classic Rock', 'Progressive Rock', 'Punk Rock', 'Alternative Rock', 'Heavy Metal'],
  'Classic Rock': [],
  'Progressive Rock': [],
  'Punk Rock': [],
  'Alternative Rock': [],
  'Heavy Metal': [],
  'Pop': [],
  'World Music': [],
  'Electronic Music': [],
  'Music Theory': [],
  'Composition': [],
  'Design': ['Industrial Design', 'Fashion Design', 'Interaction Design', 'Game Design'],
  'Industrial Design': [],
  'Fashion Design': [],
  'Interaction Design': [],
  'Game Design': [],
  'Languages': ['Indo-European Languages', 'Sino-Tibetan Languages', 'Afro-Asiatic Languages', 'Austronesian Languages', 'Altaic Languages', 'Grammar', 'Linguistics', 'Translation', 'Phonetics', 'Semantics'],
  'Indo-European Languages': [],
  'Sino-Tibetan Languages': [],
  'Afro-Asiatic Languages': [],
  'Austronesian Languages': [],
  'Altaic Languages': [],
  'Grammar': [],
  'Linguistics': [],
  'Translation': [],
  'Phonetics': [],
  'Semantics': [],
  'Physics': ['Mechanics', 'Thermodynamics', 'Electromagnetism', 'Optics', 'Quantum Physics', 'Relativity'],
  'Mechanics': ['Classical Mechanics', 'Kinematics', 'Dynamics', 'Statics', 'Fluid Dynamics', 'Wave Motion'],
  'Classical Mechanics': [],
  'Kinematics': [],
  'Dynamics': [],
  'Statics': [],
  'Fluid Dynamics': [],
  'Wave Motion': [],
  'Thermodynamics': ['First Law', 'Second Law', 'Entropy', 'Heat Transfer', 'Phase Transitions', 'Cryogenics'],
  'First Law': [],
  'Second Law': [],
  'Entropy': [],
  'Heat Transfer': [],
  'Phase Transitions': [],
  'Cryogenics': [],
  'Electromagnetism': ['Electric Fields', 'Magnetic Fields', 'Maxwell Equations', 'Light', 'Radiation', 'Plasma'],
  'Electric Fields': [],
  'Magnetic Fields': [],
  'Maxwell Equations': [],
  'Light': [],
  'Radiation': [],
  'Plasma': [],
  'Optics': ['Geometric Optics', 'Wave Optics', 'Quantum Optics', 'Photonics', 'Lasers', 'Color'],
  'Geometric Optics': [],
  'Wave Optics': [],
  'Quantum Optics': [],
  'Photonics': [],
  'Lasers': [],
  'Color': [],
  'Quantum Physics': ['Wave-Particle Duality', 'Superposition', 'Entanglement', 'Uncertainty Principle', 'Quantum Computing', 'Quantum Field Theory'],
  'Wave-Particle Duality': [],
  'Superposition': [],
  'Entanglement': [],
  'Uncertainty Principle': [],
  'Quantum Computing': [],
  'Quantum Field Theory': [],
  'Relativity': ['Special Relativity', 'General Relativity', 'Spacetime', 'Gravity', 'Black Holes', 'Cosmological Constant'],
  'Special Relativity': [],
  'General Relativity': [],
  'Spacetime': [],
  'Gravity': [],
  'Cosmological Constant': [],
  'Chemistry': ['Organic Chemistry', 'Inorganic Chemistry', 'Physical Chemistry', 'Biochemistry', 'Analytical Chemistry', 'Materials Science'],
  'Organic Chemistry': ['Hydrocarbons', 'Functional Groups', 'Reactions', 'Synthesis', 'Natural Products', 'Polymers'],
  'Hydrocarbons': [],
  'Functional Groups': [],
  'Reactions': [],
  'Synthesis': [],
  'Natural Products': [],
  'Polymers': [],
  'Inorganic Chemistry': ['Main Group Chemistry', 'Transition Metals', 'Coordination Chemistry', 'Solid State Chemistry', 'Crystal Chemistry', 'Geochemistry'],
  'Main Group Chemistry': [],
  'Transition Metals': [],
  'Coordination Chemistry': [],
  'Solid State Chemistry': [],
  'Crystal Chemistry': [],
  'Geochemistry': [],
  'Physical Chemistry': ['Kinetics', 'Quantum Chemistry', 'Spectroscopy', 'Electrochemistry', 'Surface Chemistry'],
  'Kinetics': [],
  'Quantum Chemistry': [],
  'Spectroscopy': [],
  'Electrochemistry': [],
  'Surface Chemistry': [],
  'Biochemistry': ['Proteins', 'Carbohydrates', 'Lipids', 'Nucleic Acids', 'Enzymes', 'Metabolism'],
  'Proteins': [],
  'Carbohydrates': [],
  'Lipids': [],
  'Nucleic Acids': [],
  'Enzymes': [],
  'Metabolism': [],
  'Analytical Chemistry': [],
  'Materials Science': [],
  'Biology': ['Botany', 'Zoology', 'Microbiology', 'Genetics', 'Ecology', 'Molecular Biology'],
  'Botany': ['Plant Structure', 'Plant Physiology', 'Plant Reproduction', 'Plant Ecology', 'Agricultural Botany', 'Ethnobotany'],
  'Plant Structure': [],
  'Plant Physiology': [],
  'Plant Reproduction': [],
  'Plant Ecology': [],
  'Agricultural Botany': [],
  'Ethnobotany': [],
  'Zoology': ['Vertebrate Zoology', 'Invertebrate Zoology', 'Animal Behavior', 'Animal Physiology', 'Comparative Anatomy', 'Evolution'],
  'Vertebrate Zoology': [],
  'Invertebrate Zoology': [],
  'Animal Behavior': [],
  'Animal Physiology': [],
  'Comparative Anatomy': [],
  'Evolution': [],
  'Microbiology': ['Bacteriology', 'Virology', 'Mycology', 'Parasitology', 'Microbial Ecology', 'Microbial Genetics'],
  'Bacteriology': [],
  'Virology': [],
  'Mycology': [],
  'Parasitology': [],
  'Microbial Ecology': [],
  'Microbial Genetics': [],
  'Genetics': ['Classical Genetics', 'Molecular Genetics', 'Population Genetics', 'Quantitative Genetics', 'Evolutionary Genetics', 'Human Genetics'],
  'Classical Genetics': [],
  'Molecular Genetics': [],
  'Population Genetics': [],
  'Quantitative Genetics': [],
  'Evolutionary Genetics': [],
  'Human Genetics': [],
  'Ecology': ['Population Ecology', 'Community Ecology', 'Ecosystem Ecology', 'Biogeography', 'Conservation Biology', 'Restoration Ecology'],
  'Population Ecology': [],
  'Community Ecology': [],
  'Ecosystem Ecology': [],
  'Biogeography': [],
  'Conservation Biology': [],
  'Restoration Ecology': [],
  'Molecular Biology': ['DNA', 'RNA', 'Protein Synthesis', 'Gene Expression', 'Cell Biology', 'Developmental Biology'],
  'DNA': [],
  'RNA': [],
  'Protein Synthesis': [],
  'Gene Expression': [],
  'Cell Biology': [],
  'Developmental Biology': [],
  'Mathematics': ['Algebra', 'Geometry', 'Calculus', 'Statistics', 'Number Theory'],
  'Algebra': ['Linear Algebra', 'Abstract Algebra', 'Commutative Algebra', 'Homological Algebra', 'Representation Theory', 'Category Theory'],
  'Linear Algebra': [],
  'Abstract Algebra': [],
  'Commutative Algebra': [],
  'Homological Algebra': [],
  'Representation Theory': [],
  'Category Theory': [],
  'Geometry': ['Euclidean Geometry', 'Non-Euclidean Geometry', 'Differential Geometry', 'Algebraic Geometry', 'Topology', 'Discrete Geometry'],
  'Euclidean Geometry': [],
  'Non-Euclidean Geometry': [],
  'Differential Geometry': [],
  'Algebraic Geometry': [],
  'Topology': [],
  'Discrete Geometry': [],
  'Calculus': ['Differential Calculus', 'Integral Calculus', 'Multivariable Calculus', 'Complex Analysis', 'Functional Analysis', 'Harmonic Analysis'],
  'Differential Calculus': [],
  'Integral Calculus': [],
  'Multivariable Calculus': [],
  'Complex Analysis': [],
  'Functional Analysis': [],
  'Harmonic Analysis': [],
  'Statistics': ['Probability', 'Descriptive Statistics', 'Inferential Statistics', 'Regression', 'Bayesian Statistics', 'Experimental Design'],
  'Probability': [],
  'Descriptive Statistics': [],
  'Inferential Statistics': [],
  'Regression': [],
  'Bayesian Statistics': [],
  'Experimental Design': [],
  'Number Theory': ['Prime Numbers', 'Modular Arithmetic', 'Diophantine Equations', 'Cryptography', 'Analytic Number Theory', 'Algebraic Number Theory'],
  'Prime Numbers': [],
  'Modular Arithmetic': [],
  'Diophantine Equations': [],
  'Cryptography': [],
  'Analytic Number Theory': [],
  'Algebraic Number Theory': [],
  'Earth Science': ['Geology', 'Meteorology', 'Oceanography', 'Mineralogy', 'Seismology', 'Paleontology'],
  'Geology': ['Plate Tectonics', 'Rock Formation', 'Mineral Science', 'Structural Geology', 'Stratigraphy', 'Geomorphology'],
  'Plate Tectonics': [],
  'Rock Formation': [],
  'Mineral Science': [],
  'Structural Geology': [],
  'Stratigraphy': [],
  'Geomorphology': [],
  'Meteorology': ['Atmospheric Composition', 'Weather Patterns', 'Climate Systems', 'Storms', 'Air Pollution', 'Climate Change'],
  'Atmospheric Composition': [],
  'Weather Patterns': [],
  'Climate Systems': [],
  'Storms': [],
  'Air Pollution': [],
  'Climate Change': [],
  'Oceanography': [],
  'Mineralogy': [],
  'Seismology': [],
  'Paleontology': [],
  'Astronomy': ['Observational Astronomy', 'Planetary Science', 'Stellar Astronomy', 'Galactic Astronomy', 'Extragalactic Astronomy', 'Cosmology'],
  'Observational Astronomy': [],
  'Planetary Science': ['Inner Planets', 'Outer Planets', 'Moons', 'Asteroids', 'Comets', 'Exoplanets'],
  'Inner Planets': [],
  'Outer Planets': [],
  'Moons': [],
  'Asteroids': [],
  'Comets': [],
  'Exoplanets': [],
  'Stellar Astronomy': ['Star Formation', 'Star Life Cycle', 'Stellar Classification', 'Binary Stars', 'Pulsars', 'Neutron Stars'],
  'Star Formation': [],
  'Star Life Cycle': [],
  'Stellar Classification': [],
  'Binary Stars': [],
  'Pulsars': [],
  'Neutron Stars': [],
  'Galactic Astronomy': [],
  'Extragalactic Astronomy': [],
  'Cosmology': ['Origin of Universe', 'Structure of Universe', 'Big Bang', 'Black Holes', 'Dark Matter', 'Multiverse'],
  'Origin of Universe': [],
  'Structure of Universe': [],
  'Big Bang': [],
  'Black Holes': [],
  'Dark Matter': [],
  'Multiverse': [],
};

export default TOPIC_SUBDIVISIONS;
